import { useEffect, useState, type FormEvent } from 'react';
import { ApiError, apiFetch } from '../../lib/api';
interface Contribution { id:string; title:string; kind:string; status:string; rejection_reason:string|null; created_at:number; }
export function ContributionPage(){
 const [items,setItems]=useState<Contribution[]>([]);const [title,setTitle]=useState('');const [kind,setKind]=useState('image');const [externalUrl,setExternalUrl]=useState('');const [extractionCode,setExtractionCode]=useState('');const [share,setShare]=useState('10');const [note,setNote]=useState('');const [notice,setNotice]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
 async function load(){try{const p=await apiFetch<{contributions:Contribution[]}>('/contributions/mine');setItems(p.contributions)}catch{setError('投稿记录加载失败')}} useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(null);setNotice(null);try{await apiFetch('/contributions',{method:'POST',body:{title,kind,externalUrl,extractionCode:extractionCode||undefined,requestedSharePercent:Number(share),note:note||undefined}});setNotice('投稿已提交，等待审核');setTitle('');setExternalUrl('');setExtractionCode('');setNote('');await load()}catch(c){setError(c instanceof ApiError?c.message:'投稿失败')}finally{setBusy(false)}}
 return <section className="course-page"><header className="course-page__header"><h1>合作投稿</h1><p>首版支持图片、视频和已解锁的 ZIP 网盘链接投稿。</p></header>{notice?<div className="alert alert--success" role="status">{notice}</div>:null}{error?<div className="alert alert--error" role="alert">{error}</div>:null}<form className="card form" onSubmit={submit}><div className="field"><label htmlFor="contribution-title">资源名称</label><input id="contribution-title" value={title} onChange={e=>setTitle(e.target.value)} required/></div><div className="field"><label htmlFor="contribution-kind">投稿类型</label><select id="contribution-kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="image">图片</option><option value="video">视频</option><option value="zip">ZIP</option></select></div><div className="field"><label htmlFor="contribution-url">网盘链接</label><input id="contribution-url" type="url" value={externalUrl} onChange={e=>setExternalUrl(e.target.value)} required/></div><div className="field"><label htmlFor="contribution-code">提取码</label><input id="contribution-code" value={extractionCode} onChange={e=>setExtractionCode(e.target.value)}/></div><div className="field"><label htmlFor="contribution-share">期望分成（%）</label><input id="contribution-share" type="number" min="0" max="100" value={share} onChange={e=>setShare(e.target.value)} required/></div><div className="field"><label htmlFor="contribution-note">备注</label><textarea id="contribution-note" value={note} onChange={e=>setNote(e.target.value)}/></div><button className="button button--primary" disabled={busy}>提交投稿</button></form><div className="card"><h2>我的投稿</h2>{items.length===0?<p className="empty-state">暂无投稿</p>:<ul className="comments__list">{items.map(item=><li className="comment-item" key={item.id}><strong>{item.title}</strong><p>{item.kind} · {item.status}</p>{item.rejection_reason?<p>{item.rejection_reason}</p>:null}</li>)}</ul>}</div></section>;
}
