import type { Env } from '../env'; import { ApiError } from '../middleware/error';
export async function getWallet(env:Env,userId:string){const rows=await env.DB.prepare('SELECT source,status,SUM(amount_cents) AS amount FROM earning_entries WHERE user_id=? GROUP BY source,status').bind(userId).all<{source:string;status:string;amount:number}>(); return rows.results??[];}
export async function listNotifications(env:Env,userId:string){const r=await env.DB.prepare('SELECT id,type,title,body,link,read_at,created_at FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(userId).all();return r.results??[];}
export async function markNotificationsRead(env:Env,userId:string){await env.DB.prepare('UPDATE notifications SET read_at=? WHERE user_id=? AND read_at IS NULL').bind(Date.now(),userId).run();}
export async function listWithdrawals(env:Env,userId:string){const r=await env.DB.prepare('SELECT id,amount_cents,fee_cents,net_cents,method,status,rejection_reason,created_at FROM withdrawals WHERE user_id=? ORDER BY created_at DESC').bind(userId).all();return r.results??[];}
export async function createWithdrawal(env:Env,userId:string,input:{amountCents:number;method:'wechat'|'alipay';account:string;note?:string|undefined}){if(input.amountCents<=0)throw new ApiError('invalid_amount','提现金额必须大于 0',400);const totals=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN status='available' THEN amount_cents WHEN status='frozen' THEN -amount_cents ELSE 0 END),0) AS available FROM earning_entries WHERE user_id=?").bind(userId).first<{available:number}>();if((totals?.available??0)<input.amountCents)throw new ApiError('insufficient_balance','可用余额不足',409);const fee=input.amountCents<10000?Math.round(input.amountCents/100):0;const now=Date.now();const id=crypto.randomUUID();await env.DB.batch([env.DB.prepare('INSERT INTO withdrawals (id,user_id,amount_cents,fee_cents,net_cents,method,account,note,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,userId,input.amountCents,fee,input.amountCents-fee,input.method,input.account.trim(),input.note?.trim()||null,'pending',now,now),env.DB.prepare("INSERT INTO earning_entries (id,user_id,source,amount_cents,status,note,created_at,updated_at) VALUES (?,?,'contribution',?,'frozen',?,?,?)").bind(crypto.randomUUID(),userId,-input.amountCents,'提现冻结',now,now)]);return {id,amountCents:input.amountCents,feeCents:fee,netCents:input.amountCents-fee,status:'pending'};}

export async function listWithdrawalsForAdmin(env:Env){const r=await env.DB.prepare("SELECT w.*, u.username, u.display_name FROM withdrawals w JOIN users u ON u.id=w.user_id WHERE w.status='pending' ORDER BY w.created_at").all();return r.results??[];}
export async function reviewWithdrawal(env:Env,reviewerId:string,id:string,decision:'approve'|'reject',reason?:string){const w=await env.DB.prepare('SELECT * FROM withdrawals WHERE id=?').bind(id).first<{user_id:string;amount_cents:number;status:string}>();if(!w)throw new ApiError('withdrawal_not_found','提现申请不存在',404);if(w.status!=='pending')throw new ApiError('invalid_state','提现申请已处理',409);const now=Date.now();const status=decision==='approve'?'approved':'rejected';await env.DB.batch([env.DB.prepare('UPDATE withdrawals SET status=?,rejection_reason=?,reviewed_by=?,reviewed_at=?,updated_at=? WHERE id=? AND status=\'pending\'').bind(status,decision==='reject'?reason?.trim()||'未通过':null,reviewerId,now,now,id),env.DB.prepare(status==='approved'?"UPDATE earning_entries SET status='withdrawn',updated_at=? WHERE user_id=? AND status='frozen' AND amount_cents=?":"UPDATE earning_entries SET status='available',updated_at=? WHERE user_id=? AND status='frozen' AND amount_cents=?").bind(now,w.user_id,-w.amount_cents)]);return {id,status};}
